name: Tests And Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry and setup environment with it
        run: |
          pip install pip --upgrade
          pip install poetry

          poetry install

          pip install tox tox-gh-actions

      - name: Run Tox
        run: tox